# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [15]:
# Create a 1-dimensional NumPy array using np.array()
arr_1 = np.array([1, 2, 3, 4])
# Create a 2-dimensional NumPy array using np.array()
arr_2 = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
# Create a 3-dimensional Numpy array using np.array()
arr_3 = np.array([[1, 2, 3, 4], [3, 2, 3, 1], [5, 2, 3, 4]])

print(arr_1)
print(arr_2)
print(arr_3)

[1 2 3 4]
[[1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4]
 [3 2 3 1]
 [5 2 3 4]]


Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [25]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("Shape", arr_1.shape)
print("Dimensions", arr_1.ndim)
print("Data type", arr_1.dtype)
print("Size", arr_1.size)
print("Type", arr_1.dtype.type)

Shape (4,)
Dimensions 1
Data type int64
Size 4
Type <class 'numpy.int64'>


In [29]:
# Attributes of 2-dimensional array
print("Shape", arr_2.shape)
print("Dimensions", arr_2.ndim)
print("Data type", arr_2.dtype)
print("Size", arr_2.size)
print("Type", arr_2.dtype.type)

Shape (2, 4)
Dimensions 2
Data type int64
Size 8
Type <class 'numpy.int64'>


In [30]:
# Attributes of 3-dimensional array
print("Shape", arr_3.shape)
print("Dimensions", arr_3.ndim)
print("Data type", arr_3.dtype)
print("Size", arr_3.size)
print("Type", arr_3.dtype.type)

Shape (3, 4)
Dimensions 2
Data type int64
Size 12
Type <class 'numpy.int64'>


In [41]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
data = pd.DataFrame({'A': [1, 2, 3]})
print(data)

   A
0  1
1  2
2  3


In [53]:
# Create an array of shape (10, 2) with only ones
arr_only1 = np.ones((10,2))
print(arr_only1, arr_only1.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] (10, 2)


In [52]:
# Create an array of shape (7, 2, 3) of only zeros
arr_only0 = np.zeros((7,2,3))
print(arr_only0, arr_only0.shape)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]] (7, 2, 3)


In [59]:
# Create an array within a range of 0 and 100 with step 3
import random
arr_4 = np.arange(0,100,3)
print(arr_4)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [67]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_5 = np.random.randint(0,10, [7,2])
print(arr_5, arr_5.size)

[[0 1]
 [7 4]
 [6 7]
 [7 2]
 [8 7]
 [2 6]
 [7 4]] 14


In [76]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_6 = np.random.ranf([3, 5])
print(arr_6, arr_6.size)

[[0.11153882 0.89802408 0.07810861 0.5670639  0.45009327]
 [0.57081904 0.93864295 0.71213156 0.45095242 0.43062641]
 [0.91865196 0.9320118  0.40215319 0.46082764 0.75502996]] 15


In [86]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_7 = np.random.randint(0,10, [4,6])
print(arr_7)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [92]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr_8 = np.random.randint(1,10, [3,7])
print(arr_8, arr_8.size)

# Find the unique numbers in the array you just created
print(np.unique(arr_8))


[[7 1 1 9 9 4 9]
 [3 7 6 8 9 5 1]
 [3 8 6 8 9 4 1]] 21
[1 3 4 5 6 7 8 9]


In [100]:
# Find the 0'th index of the latest array you created
print(arr_8[0,0])

7


In [108]:
# Get the first 2 rows of latest array you created
arr_8[0:2]

array([[7, 1, 1, 9, 9, 4, 9],
       [3, 7, 6, 8, 9, 5, 1]], dtype=int32)

In [124]:
# Get the first 2 values of the first 2 rows of the latest array
print(arr_8[0:2,0:1])

[[7]
 [3]]


In [132]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_9 = np.random.randint(0,10, [3,5])
arr_10 = np.ones((3,5))
print(arr_9)
print(arr_10)

[[3 7 7 6 2]
 [0 0 2 5 6]
 [5 5 5 2 5]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [141]:
# Add the two arrays together
arr_add = np.add(arr_9, arr_10)

In [137]:
# Create another array of ones of shape (5, 3)
arr_11 = np.ones((5,3))
print(arr_11)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [147]:
# Try add the array of ones and the other most recent array together
#print(np.add(arr_11, arr_add))
arr_resize = np.resize(arr_11,(3,5))
arr_resize_add = np.add(arr_resize, arr_add)
print(arr_resize_add)

[[5. 9. 9. 8. 4.]
 [2. 2. 4. 7. 8.]
 [7. 7. 7. 4. 7.]]


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [139]:
# Create another array of ones of shape (3, 5)
arr_12 = np.ones((3,5))

In [150]:
# Subtract the new array of ones from the other most recent array
arr_sub = np.subtract(arr_resize_add, arr_12)
print(arr_sub)

[[4. 8. 8. 7. 3.]
 [1. 1. 3. 6. 7.]
 [6. 6. 6. 3. 6.]]


In [23]:
# Multiply the ones array with the latest array
arr_mul = np.multiply()

In [24]:
# Take the latest array to the power of 2 using '**'


In [25]:
# Do the same thing with np.square()


In [26]:
# Find the mean of the latest array using np.mean()


In [27]:
# Find the maximum of the latest array using np.max()


In [28]:
# Find the minimum of the latest array using np.min()


In [29]:
# Find the standard deviation of the latest array


In [30]:
# Find the variance of the latest array


In [31]:
# Reshape the latest array to (3, 5, 1)


In [32]:
# Transpose the latest array


What does the transpose do?

In [33]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)


In [34]:
# Perform a dot product on the two newest arrays you created


In [35]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)


In [36]:
# Perform a dot product on the two newest arrays you created


It doesn't work. How would you fix it?

In [37]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [38]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [39]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [40]:
# Compare the two arrays with '>='


In [41]:
# Find which elements of the first array are greater than 7


In [42]:
# Which parts of each array are equal? (try using '==')


In [43]:
# Sort one of the arrays you just created in ascending order


In [44]:
# Sort the indexes of one of the arrays you just created


In [45]:
# Find the index with the maximum value in one of the arrays you've created


In [46]:
# Find the index with the minimum value in one of the arrays you've created


In [47]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [48]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [49]:
# Create an array of normally distributed random numbers


In [50]:
# Create an array with 10 evenly spaced numbers between 1 and 100


# Pandas Practice

This notebook is dedicated to practicing different tasks with pandas. The solutions are available in a solutions notebook, however, you should always try to figure them out yourself first.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to pandas notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/).

In [1]:
# Import pandas


In [2]:
# Create a series of three different colours


In [3]:
# View the series of different colours


In [4]:
# Create a series of three different car types and view it


In [5]:
# Combine the Series of cars and colours into a DataFrame


In [6]:
# Import "../data/car-sales.csv" and turn it into a DataFrame


**Note:** Since you've imported `../data/car-sales.csv` as a DataFrame, we'll now refer to this DataFrame as 'the car sales DataFrame'.

In [7]:
# Export the DataFrame you created to a .csv file


In [8]:
# Find the different datatypes of the car data DataFrame


In [9]:
# Describe your current car sales DataFrame using describe()


In [10]:
# Get information about your DataFrame using info()


What does it show you?

In [11]:
# Create a Series of different numbers and find the mean of them


In [12]:
# Create a Series of different numbers and find the sum of them


In [13]:
# List out all the column names of the car sales DataFrame


In [14]:
# Find the length of the car sales DataFrame


In [15]:
# Show the first 5 rows of the car sales DataFrame


In [16]:
# Show the first 7 rows of the car sales DataFrame


In [17]:
# Show the bottom 5 rows of the car sales DataFrame


In [18]:
# Use .loc to select the row at index 3 of the car sales DataFrame


In [19]:
# Use .iloc to select the row at position 3 of the car sales DataFrame


Notice how they're the same? Why do you think this is? 

Check the pandas documentation for [.loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [.iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html). Think about a different situation each could be used for and try them out.

In [20]:
# Select the "Odometer (KM)" column from the car sales DataFrame


In [21]:
# Find the mean of the "Odometer (KM)" column in the car sales DataFrame


In [22]:
# Select the rows with over 100,000 kilometers on the Odometer


In [23]:
# Create a crosstab of the Make and Doors columns


In [24]:
# Group columns of the car sales DataFrame by the Make column and find the average


In [25]:
# Import Matplotlib and create a plot of the Odometer column
# Don't forget to use %matplotlib inline


In [26]:
# Create a histogram of the Odometer column using hist()


In [27]:
# Try to plot the Price column using plot()


Why didn't it work? Can you think of a solution?

You might want to search for "how to convert a pandas string column to numbers".

And if you're still stuck, check out this [Stack Overflow question and answer on turning a price column into integers](https://stackoverflow.com/questions/44469313/price-column-object-to-int-in-pandas).

See how you can provide the example code there to the problem here.

In [28]:
# Remove the punctuation from price column


In [29]:
# Check the changes to the price column


In [30]:
# Remove the two extra zeros at the end of the price column


In [31]:
# Check the changes to the Price column


In [32]:
# Change the datatype of the Price column to integers


In [33]:
# Lower the strings of the Make column


If you check the car sales DataFrame, you'll notice the Make column hasn't been lowered.

How could you make these changes permanent?

Try it out.

In [34]:
# Make lowering the case of the Make column permanent


In [35]:
# Check the car sales DataFrame


Notice how the Make column stays lowered after reassigning.

Now let's deal with missing data.

In [36]:
# Import the car sales DataFrame with missing data ("../data/car-sales-missing-data.csv")


# Check out the new DataFrame


Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.

In [37]:
# Fill the Odometer column missing values with the mean of the column inplace


In [38]:
# View the car sales missing DataFrame and verify the changes


In [39]:
# Remove the rest of the missing data inplace


In [40]:
# Verify the missing values are removed by viewing the DataFrame


We'll now start to add columns to our DataFrame.

In [41]:
# Create a "Seats" column where every row has a value of 5


In [42]:
# Create a column called "Engine Size" with random values between 1.3 and 4.5
# Remember: If you're doing it from a Python list, the list has to be the same length
# as the DataFrame


In [43]:
# Create a column which represents the price of a car per kilometer
# Then view the DataFrame


In [44]:
# Remove the last column you added using .drop()


In [45]:
# Shuffle the DataFrame using sample() with the frac parameter set to 1
# Save the the shuffled DataFrame to a new variable


Notice how the index numbers get moved around. The [`sample()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) function is a great way to get random samples from your DataFrame. It's also another great way to shuffle the rows by setting `frac=1`.

In [46]:
# Reset the indexes of the shuffled DataFrame


Notice the index numbers have been changed to have order (start from 0).

In [47]:
# Change the Odometer values from kilometers to miles using a Lambda function
# Then view the DataFrame


In [48]:
# Change the title of the Odometer (KM) to represent miles instead of kilometers
